# Generated by Django 5.2.4 on 2025-07-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='created',
            new_name='created_at',
        ),
    ]
